"""openssl/openssl — the strongest memory-safety case in open source, and the
report still declines to authorize the rewrite.

Repository facts were measured read-only on the shallow clone named in
`repository`.
"""

CASE = {
    "slug": "openssl",
    "project_name": "openssl/openssl",
    "project_desc": ("C · TLS and crypto library · 808,625 lines of C · 6,357 exported ABI symbols",
                     "C · TLS 与密码学库 · 808,625 行 C · 6,357 个导出 ABI 符号"),
    "date": "2026-08-01",
    "archetype": ("security-parser · library under a checksum-pinned FIPS validation boundary",
                  "安全解析器 · 处在 checksum 锁定的 FIPS 验证边界内的库"),

    "scope_word": "STAY",
    "auth": "DEFER–MEASURE",
    "confidence": "LOW",
    "robustness": "INDETERMINATE",
    "selected": "stay-measure",
    "scope_chip": ("no Rust scope authorized until the component attribution exists",
                   "组件归因文档出现之前，不授权任何 Rust 范围"),
    "scope_sub": ("stay while the one missing document gets produced",
                  "先不动，把缺的那份文档做出来"),

    "why": (
        "The requirement holds. The mechanism is the textbook one: C parsing attacker-controlled "
        "DER at a network trust boundary. What nobody has published is OpenSSL's advisory history "
        "split by component and root cause, so \"rewrite the 16,350 lines of crypto/asn1\" and "
        "\"rewrite all 808,625\" rest on identical evidence — none. And no proposed scope has a "
        "delivery plan for 6,357 exported symbols and a checksum-pinned FIPS module.",
        "需求成立。机制也是教科书式的：C 代码在网络信任边界上解析攻击者可控的 DER。真正缺的那份东西没有人公开过，"
        "就是按组件和根因拆开的 OpenSSL advisory 历史。于是「重写 crypto/asn1 那 16,350 行」和「把 808,625 行全部重写」"
        "靠的是同一份证据，也就是没有证据。而且到目前为止，没有哪个提案为 6,357 个导出符号和被 checksum 锁定的 "
        "FIPS 模块给出过交付方案。"
    ),
    "trigger": (
        "INDETERMINATE by construction: nobody has produced the evidence that would settle it. Two "
        "documents reopen the decision. First, the advisory history split by component and by "
        "eliminated-by-construction / downgraded-to-safe-failure / language-independent. Second, a "
        "FIPS impact analysis for the candidate component. If the class concentrates in the decoders, "
        "the authorized scope becomes EXTRACT behind the existing ABI — never MIGRATE.",
        "INDETERMINATE 是结构性的：能给出结论的证据还没有人做出来。两份文档可以重开这个决策。第一份，"
        "把 advisory 历史按组件、并按 eliminated-by-construction / downgraded-to-safe-failure / "
        "language-independent 拆开。第二份，候选组件的 FIPS 影响分析。如果这类缺陷确实集中在解析器上，"
        "被授权的范围就是在现有 ABI 后面做 EXTRACT，而不会是 MIGRATE。"
    ),

    "gates": [
        {"id": "G1", "state": "PASS", "short": ("Requirement", "需求"),
         "hero_evidence": ("C decodes attacker-controlled DER and TLS records.",
                           "C 代码在解析攻击者可控的 DER 与 TLS 记录。"),
         "name": "requirement",
         "evidence": "crypto/asn1 (16,350 lines of .c) and crypto/x509 (33,494) decode attacker-supplied structures; ssl/ (115,280 lines) terminates untrusted records. The exposure is structural."},
        {"id": "G2", "state": "UNKNOWN", "short": ("Causality", "因果"),
         "hero_evidence": ("No published split of advisories by component or root cause.",
                           "没有任何公开资料把 advisory 按组件或根因拆开。"),
         "name": "rust-specific causality",
         "evidence": "Rust removes the memory-unsafety class from the code it replaces. Which code, and how much of OpenSSL's advisory history that would have covered, is published nowhere. The causal share can only be assumed."},
        {"id": "G3", "state": "UNKNOWN", "short": ("Economics", "经济性"),
         "hero_evidence": ("Candidate scopes span 16,350 to 808,625 lines.",
                           "候选范围从 16,350 行一直到 808,625 行。"),
         "name": "economics and smallest sufficient option",
         "evidence": "Without G2's attribution there is no way to name the smallest sufficient option. A 2% decoder extraction and a 100% rewrite differ by two orders of magnitude in cost, and both rest on the same evidence: none."},
        {"id": "G4", "state": "FAIL", "short": ("Delivery", "交付"),
         "hero_evidence": ("6,357 exported symbols; FIPS sources are checksum-pinned.",
                           "6,357 个导出符号；FIPS 源码被 checksum 锁定。"),
         "name": "delivery and reversibility",
         "evidence": "No proposed Rust scope has a delivery plan for 5,729 libcrypto plus 628 libssl exported symbols across 144 public headers, nor for a FIPS provider whose source manifest is checksummed for validation. The measure step carries no delivery risk of its own."},
    ],

    "tiles": [
        (("Exported ABI symbols", "导出 ABI 符号"), "6,357", ("symbols", "个"),
         ("util/libcrypto.num 5,729 + util/libssl.num 628", "util/libcrypto.num 5,729 + util/libssl.num 628")),
        (("Attacker-facing decoders", "面向攻击者的解析器"), "49,844", ("lines", "行"),
         ("crypto/asn1 + crypto/x509 .c · 6.2% of the .c total", "crypto/asn1 + crypto/x509 的 .c · 占 .c 总量 6.2%")),
        (("Hand-tuned asm generators", "手写汇编生成器"), "257,523", ("lines", "行"),
         ("crypto/**/asm/*.pl · 213 perlasm files", "crypto/**/asm/*.pl · 213 个 perlasm 文件")),
        (("FIPS module", "FIPS 模块"), "checksum", ("pinned", "已锁定"),
         ("providers/fips-sources.checksums · validation boundary", "providers/fips-sources.checksums · 验证边界")),
        (("Candidate scope spread", "候选范围跨度"), "16,350–808,625", ("lines", "行"),
         ("why robustness is INDETERMINATE", "robustness 判为 INDETERMINATE 的原因")),
        (("In-repo test material", "仓库内测试代码"), "214,064", ("lines", "行"),
         ("test/ .c and .h · 342 files", "test/ 的 .c 与 .h · 342 个文件")),
    ],

    "options_sub": ("Same objective for every option: eliminate the memory-unsafety class where OpenSSL decodes attacker-controlled input, without breaking the exported ABI or the FIPS validation.",
                    "所有方案的目标一致：在 OpenSSL 解析攻击者可控输入的地方消除内存不安全这一缺陷类，同时不破坏导出 ABI 与 FIPS 验证。"),
    "options": [
        {"id": "stay-measure", "name": ("Stay and publish the attribution", "先不动，把归因发出来"),
         "implementation": "current",
         "scope": "stay", "scope_tag": "STAY",
         "benefit_interval": ("no risk reduction yet; unblocks the decision", "暂时不降低风险；但让决策能做"),
         "one_time_cost": "weeks of analyst time", "recurring_cost": "none",
         "cost_cell": ("weeks of analysis; no recurring", "数周分析；无经常性成本"),
         "time_to_value": ("weeks", "数周"),
         "compatibility": "unchanged", "compat_cell": ("unchanged · nothing to roll back", "不变 · 没有要回滚的东西"),
         "reversibility": "n/a", "evidence_strength": "STRONG", "disposition": "selected",
         "note": ("recommended · the cheapest way to make any later option decidable",
                  "推荐 · 让后续任何方案变得可判定的最便宜做法"),
         "reason": "G2 and G3 are UNKNOWN, and this is the only option that changes that."},
        {"id": "c-harden", "name": ("Continue fuzzing, review and hardening", "继续 fuzzing、评审与加固"),
         "implementation": "current",
         "scope": "stay", "scope_tag": "STAY",
         "benefit_interval": ("reduces incidence, class stays reachable", "降低发生率，但这类缺陷仍然可达"),
         "one_time_cost": "none new", "recurring_cost": "existing security budget",
         "cost_cell": ("none new; existing budget", "无新增；用现有预算"),
         "time_to_value": ("already running", "已经在跑"),
         "compatibility": "native", "compat_cell": ("native · no risk", "原生 · 无风险"),
         "reversibility": "n/a",
         "evidence_strength": "MODERATE", "disposition": "retain",
         "note": ("retain · the funded baseline any Rust option must beat",
                  "保留 · 有预算的基线，任何 Rust 方案都要赢过它"),
         "reason": "Runs today and must be priced as the counterfactual rather than assumed away."},
        {"id": "rust-decoder-extract", "name": ("Rust DER/X.509 decoder behind the ABI", "ABI 后面的 Rust DER/X.509 解析器"),
         "implementation": "rust",
         "scope": "extract", "scope_tag": "EXTRACT",
         "benefit_interval": ("class removed in 6.2% of the .c tree, if that is where it lives",
                              "在 .c 树的 6.2% 里消除该缺陷类，前提是缺陷确实住在那里"),
         "one_time_cost": "unpriced; parity plus FIPS analysis", "recurring_cost": "Rust in the build for every platform",
         "cost_cell": ("unpriced; Rust toolchain everywhere", "未定价；每个平台都要带 Rust 工具链"),
         "time_to_value": ("unknown", "未知"),
         "compatibility": "must preserve exact error semantics",
         "compat_cell": ("same ABI · flag-selectable if dual-built", "ABI 不变 · 双构建时可用编译开关切换"),
         "reversibility": "build flag, if kept dual", "evidence_strength": "UNKNOWN", "disposition": "retain",
         "note": ("retain · the likely answer if the attribution lands where structure suggests",
                  "保留 · 如果归因落在结构所指的位置，答案大概就是它"),
         "reason": "Correct shape and smallest plausible scope, but its benefit is unmeasured and its FIPS impact unanalysed."},
        {"id": "rust-full", "name": ("Rewrite OpenSSL in Rust", "用 Rust 重写 OpenSSL"),
         "implementation": "rust", "scope": "full",
         "scope_tag": "MIGRATE",
         "benefit_interval": ("class removed; no evidence it beats the extraction",
                              "该缺陷类消失；但没有证据说明它优于抽取方案"),
         "one_time_cost": "multi-year, unbudgeted", "recurring_cost": "re-validate FIPS; two toolchains forever",
         "cost_cell": ("multi-year; FIPS re-validation", "以年计；外加 FIPS 重新验证"),
         "time_to_value": ("years", "以年计"),
         "compatibility": "6,357 symbols + 144 headers + FIPS",
         "compat_cell": ("entire ABI + validation · no rollback", "整个 ABI 加验证 · 无回滚"),
         "reversibility": "none", "evidence_strength": "WEAK", "disposition": "exclude",
         "note": ("exclude · fails G4 outright", "排除 · 直接卡死在 G4"),
         "reason": "No delivery plan exists for the exported ABI or the checksum-pinned FIPS module, and 257,523 lines of perlasm carry no part of the safety objective."},
        {"id": "adopt-rust-tls", "name": ("Consumers adopt a Rust TLS stack", "使用方改用 Rust TLS 栈"),
         "implementation": "external",
         "scope": "adopt", "scope_tag": "ADOPT",
         "benefit_interval": ("full class removal for that consumer's TLS path",
                              "该使用方的 TLS 路径上整类缺陷消失"),
         "one_time_cost": "per consumer", "recurring_cost": "narrower algorithm and platform coverage",
         "cost_cell": ("per consumer; narrower coverage", "按使用方计；覆盖面更窄"),
         "time_to_value": ("weeks per project", "每个项目数周"),
         "compatibility": "different API; FIPS varies",
         "compat_cell": ("different API · caller-side rollback", "API 不同 · 回滚在调用方手里"),
         "reversibility": "caller-side", "evidence_strength": "STRONG", "disposition": "retain",
         "note": ("retain · demonstrably works — see curl's shipped rustls backend",
                  "保留 · 已经被跑通，见 curl 已发布的 rustls 后端"),
         "reason": "Meets the objective for an individual consumer today; it is not a decision OpenSSL can make on their behalf."},
    ],

    "lenses_sub": ("States are evidence about named options, not points to be added up. D6 is UNKNOWN and stays UNKNOWN here. It sits under the two gates that decide this case, and no amount of argument closes it.",
                   "状态是针对具体方案的证据，不能相加成分数。D6 是 UNKNOWN，这里就照写 UNKNOWN。决定本案的两道门都压在它上面，靠论证关不上。"),
    "na_note": ("N/A lenses: D3 tail latency, D4 fleet footprint and D5 startup shape have no bearing on a memory-safety objective for a library that runs inside the caller's process.",
                "判为 N/A 的维度：D3 尾延迟、D4 机队占用、D5 启动形态。对一个跑在调用方进程里的库来说，它们与内存安全目标无关。"),
    "lenses": [
        {"id": "D1", "name": ("Requirement & ownership", "需求与归属"), "label": "SUPPORTS · rust options", "css": "rust",
         "state": "SUPPORTS", "strength": "STRONG", "option_ids": ["rust-decoder-extract", "rust-full", "adopt-rust-tls"],
         "claim": ("OpenSSL owns 808,625 lines of C. Of that, 49,844 lines decode attacker-supplied ASN.1 and X.509 structures and 115,280 terminate untrusted TLS records.",
                   "OpenSSL 自己维护 808,625 行 C。其中 49,844 行解析攻击者提供的 ASN.1 与 X.509 结构，115,280 行负责终结不受信任的 TLS 记录。"),
         "source": "crypto/asn1 65 .c files · crypto/x509 98 .c files · ssl/ 115 .c and .h files",
         "regime": "static structure of the shipped library",
         "caveat": "Structural exposure only; no per-component defect attribution is published."},
        {"id": "D2", "name": ("End-to-end reach", "端到端影响"), "label": "N/A", "css": "neutral",
         "state": "N/A", "strength": "STRONG", "option_ids": [],
         "claim": ("Nobody has asserted a performance requirement here. No Amdahl figure appears: a line share is not a time share, and inventing one would be a method error.",
                   "本案没有人提出性能要求。这里不给 Amdahl 数字：行数占比不等于时间占比，硬造一个属于方法错误。"),
         "source": "objective is safety, not latency", "regime": "n/a", "caveat": ""},
        {"id": "D3", "name": ("Tail & runtime", "尾延迟与运行时"), "label": "N/A", "css": "neutral",
         "state": "N/A", "strength": "STRONG", "option_ids": [],
         "claim": ("No managed runtime or collector exists in the library, so no runtime mechanism is present in any tail.",
                   "库里没有托管运行时，也没有 GC，所以尾部时延里不存在运行时机制这一项。"),
         "source": "C library, no GC", "regime": "n/a", "caveat": ""},
        {"id": "D4", "name": ("Fleet footprint", "机队占用"), "label": "N/A", "css": "neutral",
         "state": "N/A", "strength": "STRONG", "option_ids": [],
         "claim": ("The library runs inside the caller's process; this decision changes no fleet density or instance count.",
                   "库跑在调用方的进程里。这个决策不改变任何机队密度或实例数量。"),
         "source": "embedded linkage model", "regime": "n/a", "caveat": ""},
        {"id": "D5", "name": ("Startup shape", "启动形态"), "label": "N/A", "css": "neutral",
         "state": "N/A", "strength": "STRONG", "option_ids": [],
         "claim": ("Handshake round-trips dominate connection setup; library initialization is not a stated constraint here.",
                   "连接建立的时间由握手往返主导。本案没有把库初始化列为约束。"),
         "source": "no startup requirement asserted", "regime": "n/a", "caveat": ""},
        {"id": "D6", "name": ("Safety & correctness", "安全与正确性"), "label": "UNKNOWN · rust options", "css": "unknown",
         "state": "UNKNOWN", "strength": "UNKNOWN", "option_ids": ["rust-decoder-extract", "rust-full"],
         "claim": ("The classification this decision needs does not exist publicly: advisories split per component into eliminated-by-construction, downgraded-to-safe-failure and language-independent. Counting advisories is not a causal argument.",
                   "这项决策需要的分类在公开渠道里不存在：按组件把 advisory 拆成 eliminated-by-construction、downgraded-to-safe-failure、language-independent 三类。只数 advisory 的条数，构不成因果论证。"),
         "source": "no published per-component root-cause attribution",
         "regime": "n/a — the artifact is absent",
         "caveat": "This is the single gap that makes the whole decision indeterminate.",
         "change_trigger": "Publishing the classification moves G2 and G3 out of UNKNOWN and likely selects the decoder extraction."},
        {"id": "D7", "name": ("Concurrency & invariants", "并发与不变量"), "label": "NEUTRAL · all", "css": "neutral",
         "state": "NEUTRAL", "strength": "MODERATE", "option_ids": [],
         "claim": ("Thread safety is already a contract, carried by the library's own locking and init APIs. No option encodes those invariants better without changing the contract.",
                   "线程安全已经写进契约，由库自己的加锁与初始化 API 承担。在不改契约的前提下，没有哪个方案能把这些不变量表达得更好。"),
         "source": "crypto/threads_*.c · documented threading model",
         "regime": "library concurrency contract",
         "caveat": "A Rust component would have to honour the same externally visible contract."},
        {"id": "D8", "name": ("Distribution", "分发"), "label": "DISFAVORS · rust options", "css": "rust",
         "state": "DISFAVORS", "strength": "MODERATE", "option_ids": ["rust-decoder-extract", "rust-full"],
         "claim": ("OpenSSL is a system dependency on platforms where a C compiler is the only guaranteed toolchain. Putting Rust in the build narrows that set, and it lands on every distributor.",
                   "在一些平台上 OpenSSL 是系统依赖，而那里唯一有保证的工具链就是 C 编译器。把 Rust 加进构建会缩小这个平台集合，而且每一个发行方都要跟着动。"),
         "source": "Configure · config · Configurations/ platform matrix",
         "regime": "supported platform inventory",
         "caveat": "The cost differs by two orders of magnitude between one component and a full rewrite."},
        {"id": "D9", "name": ("Ecosystem & alternatives", "生态与替代方案"), "label": "SUPPORTS · adopt-rust-tls", "css": "current",
         "state": "SUPPORTS", "strength": "STRONG", "option_ids": ["adopt-rust-tls"],
         "claim": ("Production Rust TLS stacks exist and major C consumers already ship them, so the adoption path is demonstrated rather than hypothetical.",
                   "生产级 Rust TLS 栈已经存在，主要的 C 使用方也已经把它发布出去了。所以这条采用路径是有人走通的，不是设想。"),
         "source": "curl ships lib/vtls/rustls.c (1,468 lines) as a selectable backend",
         "regime": "shipped integration in another project",
         "caveat": "Algorithm coverage, platform coverage and FIPS status differ from OpenSSL's."},
        {"id": "D10", "name": ("Boundary & compatibility", "边界与兼容性"), "label": "DISFAVORS · rust-full", "css": "rust",
         "state": "DISFAVORS", "strength": "STRONG", "option_ids": ["rust-full"],
         "claim": ("The compatibility surface is 5,729 libcrypto plus 628 libssl exported symbols across 144 public headers. Callers branch on the error semantics, so those are part of the surface too.",
                   "兼容面是 144 个公开头文件里的 5,729 个 libcrypto 符号加 628 个 libssl 符号。调用方还会拿错误语义做分支判断，所以错误语义也算在这个面里。"),
         "source": "util/libcrypto.num · util/libssl.num · include/openssl/ 116 .h + 28 .h.in",
         "regime": "exported symbol manifests in this commit",
         "caveat": "One decoder behind the same ABI inherits a small share of this surface, which is why that option stays retained."},
        {"id": "D11", "name": ("Delivery economics", "交付经济性"), "label": "DISFAVORS · rust-full", "css": "rust",
         "state": "DISFAVORS", "strength": "STRONG", "option_ids": ["rust-full"],
         "claim": ("The FIPS provider ships with a checksummed source manifest. Replacing validated code is a re-validation project, not a refactor. Separately, 257,523 lines of perlasm generate the hand-tuned assembly that carries the library's performance and none of its safety objective.",
                   "FIPS provider 附带一份带 checksum 的源码清单。替换已验证的代码，走的是重新验证流程，重构那套做法覆盖不了。另外，257,523 行 perlasm 生成的是手写汇编，它们扛着库的性能，和安全目标无关。"),
         "source": "providers/fips-sources.checksums · providers/fips.checksum · crypto/**/asm/*.pl (213 files)",
         "regime": "build and validation artifacts in this commit",
         "caveat": "Not every consumer needs FIPS; every distributor-shipped OpenSSL has to decide about it."},
        {"id": "D12", "name": ("Counterfactual", "反事实基线"), "label": "SUPPORTS · c-harden, adopt-rust-tls", "css": "current",
         "state": "SUPPORTS", "strength": "MODERATE", "option_ids": ["c-harden", "adopt-rust-tls"],
         "claim": ("Two funded alternatives already run. Inside OpenSSL, continuous fuzzing and review. Outside it, consumer-side adoption of a Rust TLS stack. Both have to be beaten, not assumed away.",
                   "已经有两个带预算的替代方案在跑。OpenSSL 内部是持续 fuzzing 和代码评审，外部是使用方自己换成 Rust TLS 栈。这两个都得赢过，不能当它们不存在。"),
         "source": "existing OpenSSL security process · curl's shipped rustls backend",
         "regime": "current practice in and around the project",
         "caveat": "Neither eliminates the class inside OpenSSL itself."},
    ],

    "findings": [
        ("unknown",
         ("The document this decision needs does not exist", "这项决策需要的那份文档不存在"),
         ("Picking a Rust scope means knowing which components produced OpenSSL's memory-safety advisories, and which of those Rust would have eliminated by construction. Nobody has published that classification. So every scope from 16,350 lines to 808,625 rests on the same evidence.",
          "要选定 Rust 的范围，就得知道 OpenSSL 的内存安全 advisory 各自出自哪个组件，其中哪些是 Rust 能从构造上直接消除的。这份分类没有人公开过。于是从 16,350 行到 808,625 行，每一个候选范围拿到的都是同一份证据。"),
         "no public per-component root-cause attribution"),
        ("current",
         ("The compatibility surface is 6,357 exported symbols", "兼容面就是这 6,357 个导出符号"),
         ("util/libcrypto.num lists 5,729 exported symbols; util/libssl.num adds 628. They span 144 public headers. A rewrite owes every one of them, down to the error semantics callers branch on.",
          "util/libcrypto.num 列了 5,729 个导出符号，util/libssl.num 再加 628 个，分布在 144 个公开头文件里。重写要对其中每一个负责，细到调用方拿来做分支的错误语义。"),
         "util/libcrypto.num · util/libssl.num · include/openssl/"),
        ("current",
         ("The FIPS module's sources are checksum-pinned", "FIPS 模块的源码被 checksum 锁死"),
         ("The pinning is literal. providers/ ships fips-sources.checksums, fips.checksum and fips.module.sources. Replacing validated source starts a re-validation project on a regulatory calendar, which is a different kind of cost from engineering effort.",
          "这个锁定是字面意义上的。providers/ 里带着 fips-sources.checksums、fips.checksum 和 fips.module.sources。替换已验证的源码，等于启动一个受监管日历约束的重新验证项目，这类成本和工程投入不是一回事。"),
         "providers/fips-sources.checksums · providers/fips.module.sources"),
        ("current",
         ("257,523 lines of perlasm are not part of the safety objective", "257,523 行 perlasm 不在安全目标之内"),
         ("The hand-tuned assembly generators carry the library's throughput. A memory-safety rewrite has no reason to touch them. It cannot inherit them either. \"Rewrite OpenSSL\" and \"make OpenSSL safe\" are two different projects.",
          "这些手写汇编生成器扛着库的吞吐。以内存安全为目标的重写没有理由去动它们，也继承不了它们。「重写 OpenSSL」和「让 OpenSSL 安全」是两个项目。"),
         "crypto/**/asm/*.pl · 213 files"),
        ("rust",
         ("The attacker-facing decoders are 6.2% of the .c tree", "面向攻击者的解析器占 .c 树的 6.2%"),
         ("crypto/asn1 and crypto/x509 come to 49,844 of 808,625 lines of .c. Two directories. If the class concentrates where the structure suggests, the authorized scope is an extraction roughly sixteen times smaller than the proposal usually made.",
          "crypto/asn1 加 crypto/x509 一共 49,844 行，而 .c 总量是 808,625 行。两个目录。如果这类缺陷确实集中在结构所指的位置，那么被授权的范围是一次抽取，规模大约是常见提案的十六分之一。"),
         "crypto/asn1 16,350 + crypto/x509 33,494 lines of .c"),
    ],

    "buys": [
        (("Class elimination in decoded input handling", "解析输入这一段的整类缺陷消失"),
         ("a Rust DER/X.509 decoder cannot produce a memory-unsafety defect in its own code, at the exact place attacker bytes arrive first.",
          "Rust 写的 DER/X.509 解析器，不可能在自己的代码里产生内存不安全缺陷，而这里正是攻击者字节最先落地的位置。")),
        (("A demonstrated consumer escape hatch", "使用方有一条已经走通的退路"),
         ("callers who need memory-safe TLS today can adopt a Rust stack, as curl already does behind a build flag.",
          "今天就需要内存安全 TLS 的调用方，可以直接换 Rust 栈；curl 已经这么做了，用一个编译开关控制。")),
        (("Nothing else, yet", "目前就这些"),
         ("every wider claim in this decision is currently unmeasured, and the report labels it UNKNOWN rather than estimating it.",
          "这项决策里更大的主张全都没有测量过。报告把它们标成 UNKNOWN，而不是随手估一个数出来。")),
    ],
    "nobuys": [
        (("Throughput", "吞吐"),
         ("the performance lives in 257,523 lines of perlasm-generated assembly that a Rust rewrite would have to keep or re-create.",
          "性能落在 257,523 行由 perlasm 生成的汇编里。Rust 重写要么把它们留着，要么重造一遍。")),
        (("Relief from the ABI", "从 ABI 里解脱"),
         ("6,357 exported symbols and their error semantics survive any implementation change; they are the contract, not an implementation detail.",
          "6,357 个导出符号连同它们的错误语义，在任何实现变更之后都还在。它们本身就是契约。")),
        (("A shortcut through FIPS", "绕开 FIPS 的捷径"),
         ("the validated module's sources are checksum-pinned; changing them re-opens validation regardless of language.",
          "已验证模块的源码被 checksum 锁死。改动它就要重开验证，和用什么语言无关。")),
    ],

    "precedents": [
        {"name": "curl · rustls backend", "outcome": "EXTRACT SHIPPED",
         "body": ("A major C consumer of TLS added a Rust backend as 1,468 lines behind an abstraction that already held six of them, and kept it. The same project pushed Rust deeper into its HTTP internals, and deleted that.",
                  "一个重量级的 TLS C 使用方，在一个已经有六个后端的抽象层后面，加了 1,468 行的 Rust 后端，并且留了下来。同一个项目把 Rust 往 HTTP 内部推的那次尝试，后来被删掉了。"),
         "match": ("same trust boundary, same language pair, C caller with a stable ABI",
                   "同一条信任边界，同一对语言，调用方是带稳定 ABI 的 C"),
         "mismatch": ("curl consumes TLS; OpenSSL is the implementation with the exported ABI and FIPS obligation",
                      "curl 是 TLS 的使用方；OpenSSL 是实现方，扛着导出 ABI 和 FIPS 义务"),
         "regime": "shipped backend, curl 8.x", "source_label": "first-party · maintainer blog",
         "url": "https://daniel.haxx.se/blog/2024/12/21/dropping-hyper/"},
        {"name": "Google · Android memory-safety program", "outcome": "INCREMENTAL",
         "body": ("Memory safety's share of Android vulnerabilities fell from 76% to below 20%. The method was writing new code in safe languages and letting the old C/C++ age out. Google's own data puts five-year-old code at 3.4–7.4× lower vulnerability density than new code.",
                  "Android 漏洞里内存安全类的占比，从 76% 降到 20% 以下。做法是新代码用安全语言写，旧的 C/C++ 自然老化退场。Google 自己的数据显示，五年前写的代码，漏洞密度比新代码低 3.4–7.4 倍。"),
         "match": ("same requirement class; the strongest published safety numbers available",
                   "同一类需求；也是目前公开的安全数据里最强的一组"),
         "mismatch": ("an OS with many entry points, and the figures are C/C++-relative rather than component-attributed",
                      "那是一个入口众多的操作系统；而且那些数字是相对整体 C/C++ 算的，没有落到具体组件"),
         "regime": "2019–2025 vulnerability share", "source_label": "first-party · vendor security blog",
         "url": "https://blog.google/security/rust-in-android-move-fast-fix-things/"},
        {"name": "Chromium · memory-safety bug analysis", "outcome": "ATTRIBUTION PUBLISHED",
         "body": ("Chromium published the analysis OpenSSL has not. Of 912 high and critical security bugs since 2015, roughly 70% were memory unsafety, about half of those use-after-free. A table like that is what makes a scope decision fundable.",
                  "Chromium 公布了 OpenSSL 没有公布的那份分析。2015 年以来的 912 个高危与严重安全缺陷中，约 70% 是内存不安全，其中约一半是 use-after-free。有了这样一张表，范围决策才拿得到预算。"),
         "match": ("demonstrates the exact artifact this decision is missing",
                   "它正好就是本决策缺的那件东西"),
         "mismatch": ("a browser's bug corpus and component structure differ entirely from a crypto library's",
                      "浏览器的缺陷样本和组件结构，和密码学库完全不同"),
         "regime": "912 high/critical bugs, 2015 onward", "source_label": "first-party · project security page",
         "url": "https://www.chromium.org/Home/chromium-security/memory-safety/"},
        {"name": "Mozilla · Stylo", "outcome": "EXTRACT SHIPPED",
         "body": ("One Rust component landed inside a large C++ codebase in about two years. The move was to pick a single subsystem with a clean interface. The whole-engine replacement at the same organisation was cancelled.",
                  "一个 Rust 组件用大约两年时间落进了一个大型 C++ 代码库。关键动作是只挑一个接口干净的子系统。同一家机构里那个整引擎替换项目被取消了。"),
         "match": ("component-scoped Rust inside a large, ABI-constrained native codebase",
                   "在一个受 ABI 约束的大型原生代码库里，把 Rust 的范围限定到单个组件"),
         "mismatch": ("no exported C ABI of comparable size and no validation regime",
                      "那里没有同等规模的导出 C ABI，也没有验证合规体系"),
         "regime": "shipped in Firefox 57", "source_label": "first-party · engineer account",
         "url": "https://bholley.net/blog/2017/stylo.html"},
    ],

    "path": [
        {"title": ("Publish the advisory attribution", "把 advisory 归因发出来"),
         "body": ("The OpenSSL security team, or an independent analyst, turns the advisory history into a table: component, root cause, and one of eliminated-by-construction / downgraded-to-safe-failure / language-independent. Every advisory in the published set gets classified, and the method gets written down with it. If the public advisory text is too thin to classify, stop and say so — that answer is itself the finding. No code moves in this step.",
                  "由 OpenSSL 安全团队或一位独立分析者，把 advisory 历史整理成一张表：组件、根因，以及 eliminated-by-construction / downgraded-to-safe-failure / language-independent 三选一。公开集合里的每一条 advisory 都要归类，方法也要一并写清楚。如果公开的 advisory 文本不足以支撑分类，就停下来把这一点讲明白，这本身就是结论。这一步不动任何代码。"),
         "owner": "OpenSSL security team or an independent analyst",
         "cost_range": ("3–6 weeks", "3–6 周"),
         "artifact": "OpenSSL's advisory history as a table: component, root cause, and one of eliminated-by-construction / downgraded-to-safe-failure / language-independent",
         "acceptance": "every advisory in the published set is classified and attributed to a component, with the method stated",
         "stop": "stop and say so if public advisory text is insufficient to classify — that itself is the finding",
         "rollback": "documentation only; no code changes"},
        {"title": ("Analyse the FIPS impact of the candidate component", "分析候选组件对 FIPS 的影响"),
         "body": ("Whoever owns the validated module writes down whether replacing the candidate component's implementation crosses the module boundary, and what re-validation would cost. Two answers pass: \"outside the boundary\" with evidence, or a calendar and a price for re-validation. If the component sits inside the boundary and re-validation is unfundable, the Rust track stops here. Documentation only.",
                  "由已验证模块的负责人写清楚两件事：替换候选组件的实现会不会越过模块边界，以及重新验证要花多少。可通过的答案只有两种：有证据地说明「在边界之外」，或者给出重新验证的日历与价格。如果组件落在边界之内、而重新验证的钱拿不出来，Rust 这条线就到此为止。这一步只出文档。"),
         "owner": "whoever owns the validated module",
         "cost_range": ("2–4 weeks", "2–4 周"),
         "artifact": "a written analysis of whether replacing the candidate component's implementation crosses the validated module boundary, and what re-validation would cost",
         "acceptance": "the analysis states either 'outside the boundary' with evidence, or the calendar and cost of re-validation",
         "stop": "stop the Rust track entirely if the component is inside the boundary and re-validation is unfundable",
         "rollback": "documentation only"},
        {"title": ("Prototype one decoder behind the unchanged ABI", "在不变的 ABI 后面做一个解析器原型"),
         "body": ("Two engineers who know both C and Rust reimplement the highest-attribution decoder in Rust, exposed through the existing symbols, with a differential-fuzzing harness pointed at the C version. Passing means byte-identical accept/reject decisions and identical error codes on that corpus, plus no measured throughput regression on the library's own test workloads. Ten weeks is the limit. Miss differential parity by then and the divergences get published instead; the C implementation stays the default build and the Rust path stays a disabled build option.",
                  "两位同时熟悉 C 和 Rust 的工程师，用 Rust 重写归因最高的那个解析器，通过现有符号暴露出去，并配一套对着 C 版本跑的 differential fuzzing。通过的标准是：在那份语料上，接受/拒绝的判定逐字节一致，错误码一致，并且在库自己的测试负载上测不到吞吐回退。上限是十周。到期还没做到对照一致，就把差异公开出来收工；C 实现仍然是默认构建，Rust 路径仍然是默认关闭的构建选项。"),
         "owner": "two engineers with C and Rust experience",
         "cost_range": ("6–10 weeks", "6–10 周"),
         "artifact": "a Rust implementation of the highest-attribution decoder, exposed through the existing symbols, with a differential-fuzzing harness against the C version",
         "acceptance": "byte-identical accept/reject decisions and identical error codes on a differential-fuzzing corpus, plus no measured throughput regression on the library's own test workloads",
         "stop": "stop after ten weeks if differential parity is not reached; publish the divergences",
         "rollback": "the C implementation remains the default build; the Rust path is a disabled build option"},
        {"title": ("Re-run these gates on the new evidence", "拿新证据重跑这四道门"),
         "body": ("OpenSSL maintainers re-run the assessment against the attribution table, the FIPS analysis and the prototype's parity results. It passes when G2 and G3 leave UNKNOWN with citations attached and the selected scope is written down in words. If G2 is still UNKNOWN, authorization stays DEFER–MEASURE however good the prototype looks. Either way the C implementation stays. So does the hardening programme.",
                  "由 OpenSSL 维护者拿归因表、FIPS 分析和原型的对照结果，把评估重跑一遍。通过的标准是：G2 与 G3 带着引用离开 UNKNOWN，并且用文字写明选定的范围。如果 G2 还停在 UNKNOWN，不管原型做得多好，授权都维持 DEFER–MEASURE。无论如何，C 实现照旧保留，加固计划也照常继续。"),
         "owner": "OpenSSL maintainers",
         "cost_range": ("1 week", "1 周"),
         "artifact": "a re-assessment using the attribution table, the FIPS analysis and the prototype's parity results",
         "acceptance": "G2 and G3 leave UNKNOWN with cited evidence, and the selected scope is stated explicitly",
         "stop": "if G2 stays UNKNOWN, authorization remains DEFER–MEASURE regardless of prototype quality",
         "rollback": "the current C implementation and hardening programme continue unchanged"},
    ],

    "migration_checks": [
        {"name": ("End-to-end reach", "端到端影响"), "state": "PASS",
         "claim": ("No performance benefit is claimed here, and no Amdahl number is invented to fill the space. D2 is N/A because the objective is safety.",
                   "本案不主张性能收益，也没有为了填空造一个 Amdahl 数字。目标是安全，所以 D2 判为 N/A。"),
         "evidence": "D2 record"},
        {"name": ("Attribution", "归因"), "state": "HIT",
         "claim": ("The causal share Rust would capture cannot be located. The per-component root-cause classification is not published, so there is nothing to locate it in.",
                   "Rust 能吃下的那部分因果份额定位不了。按组件划分的根因分类没有公开，也就没有可供定位的底图。"),
         "evidence": "D6 · G2 UNKNOWN"},
        {"name": ("Baseline and regime", "基线与口径"), "state": "HIT",
         "claim": ("Structural line counts are standing in for defect distribution. That is the substitution this method forbids as a basis for authorization.",
                   "这里是用结构性的行数在顶替缺陷分布。这套方法禁止用这种顶替作为授权依据。"),
         "evidence": "D1 caveat"},
        {"name": ("Boundary and compatibility", "边界与兼容性"), "state": "PASS",
         "claim": ("6,357 exported symbols, 144 public headers, the error semantics and the checksum-pinned FIPS module are all named, and all priced against the full-rewrite option.",
                   "6,357 个导出符号、144 个公开头文件、错误语义，以及被 checksum 锁死的 FIPS 模块，全都点了名，也全都按整体重写方案算了成本。"),
         "evidence": "D10, D11 · util/libcrypto.num, providers/fips-sources.checksums"},
        {"name": ("Delivery ownership", "交付归属"), "state": "HIT",
         "claim": ("No proposed Rust scope names an owner, a dual-run plan or a re-validation calendar. The report withholds authorization rather than assume those will turn up.",
                   "现在提出的 Rust 范围，没有一个指定了负责人、双跑方案或重新验证日历。报告选择不授权，而不是假定这些东西以后会自己冒出来。"),
         "evidence": "G4 FAIL"},
    ],
    "staying_checks": [
        {"name": ("Funded counterfactual", "有预算的反事实"), "state": "PASS",
         "claim": ("Fuzzing and review inside OpenSSL, and Rust-TLS adoption outside it, are both running, both funded, and both recorded here as options.",
                   "OpenSSL 内部的 fuzzing 与评审，外部使用方改用 Rust TLS，两条路都在跑，都有预算，也都作为方案记录在案。"),
         "evidence": "D12 · c-harden, adopt-rust-tls"},
        {"name": ("Cost of inaction", "不动的代价"), "state": "HIT",
         "claim": ("Staying keeps the memory-unsafety class reachable in 49,844 lines that decode attacker-supplied structures. Nothing here presents staying as the safe choice.",
                   "不动，就意味着在 49,844 行解析攻击者提供结构的代码里，内存不安全这一类缺陷仍然可达。报告没有把「不动」写成安全的那个选择。"),
         "evidence": "D1 · G1 PASS"},
        {"name": ("Unsafe-surface omission", "遗漏的 unsafe 面"), "state": "PASS",
         "claim": ("G1 and the mechanism behind G2 are both granted to the Rust options. What the report withholds is scope selection and delivery, not the premise.",
                   "G1 以及 G2 背后的机制，报告都认给了 Rust 方案。卡住的是范围选择和交付，不是前提。"),
         "evidence": "G1 PASS, D6 mechanism"},
        {"name": ("Native-advantage denial", "对原生优势的否认"), "state": "PASS",
         "claim": ("A shipped Rust TLS integration in another major C project is cited here as working evidence, not waved off.",
                   "另一个重量级 C 项目里已经发布的 Rust TLS 接入，在这里是当作有效证据引用的，没有被打发掉。"),
         "evidence": "D9 · curl lib/vtls/rustls.c"},
        {"name": ("Stop condition", "停止条件"), "state": "PASS",
         "claim": ("DEFER–MEASURE names two documents and one prototype, each with an acceptance threshold. \"Harden C forever\" is not the default outcome.",
                   "DEFER–MEASURE 点名了两份文档和一个原型，每一项都带验收阈值。所以默认结局不会是「永远加固 C」。"),
         "evidence": "reversible path steps 1–3"},
    ],

    "gaps": [
        (("Advisory history split by component and root cause", "按组件与根因拆分的 advisory 历史"),
         ("The gap that decides the rest. While it is missing, G2 and G3 stay UNKNOWN and no Rust scope gets authorized — including the small one this report thinks is most likely right.",
          "决定其余一切的那个缺口。只要它还缺着，G2 和 G3 就停在 UNKNOWN，任何 Rust 范围都拿不到授权，包括报告认为最可能正确的那个小范围。")),
        (("FIPS boundary impact for the candidate component", "候选组件对 FIPS 边界的影响"),
         ("If the component sits inside the validated module, re-validation cost may make even the small extraction unfundable, and the answer stays STAY.",
          "如果这个组件落在已验证模块之内，重新验证的成本可能连那次小规模抽取都撑不住，结论就仍然是 STAY。")),
        (("Ownership and dual-run plan for any Rust scope", "任何 Rust 范围的负责人与双跑方案"),
         ("Without named owners and a rollback path, G4 stays FAIL for every migration option, whatever the attribution turns out to show.",
          "没有指名的负责人和回滚路径，G4 对每个迁移方案都停在 FAIL，归因最后查出什么都一样。")),
    ],

    "assumptions": [
        "The shallow clone at the named commit represents the shipped tree; the exported-symbol manifests are read as one symbol per line.",
        "OpenSSL continues to support platforms whose only guaranteed toolchain is a C compiler.",
        "No performance requirement is attached to this decision; if one appears, D2 must be recomputed from a real profile.",
    ],
    "objective": {
        "driver": "safety",
        "requirement": "eliminate the memory-unsafety class where OpenSSL decodes attacker-controlled input, without breaking the exported ABI or the FIPS validation",
        "baseline": "808,625 lines of .c, of which 49,844 decode attacker-supplied ASN.1/X.509; ssl/ adds 115,280 lines of .c and .h terminating untrusted TLS records",
        "target": "class elimination in the components where advisories concentrate — a location that is currently unpublished",
    },
    "repository": {
        "path": "https://github.com/openssl/openssl",
        "commit": "cdcb6adf8c399c14a5ee8cad5c76b6cc9e333e82",
        "scope": "whole repository; crypto/asn1 and crypto/x509 are the candidate extraction components",
        "sampling": "shallow clone; 6,152 tracked files enumerated; crypto/, ssl/, providers/, include/openssl/, util/ and test/ measured; no advisory database was ingested",
    },
    "user_supplied_facts": [],

    "method_title": ("openssl/openssl at cdcb6ad · static read-only analysis · why-not-rust method 2.0",
                     "openssl/openssl @ cdcb6ad · 只读静态分析 · why-not-rust 方法 2.0"),
    "method_body": (
        "Repository: github.com/openssl/openssl at commit cdcb6ad, shallow clone, 6,152 tracked files. "
        "Scope: the whole repository, with crypto/asn1 and crypto/x509 as the candidate extraction "
        "components. Sampling: 808,625 lines of C across 1,695 files; and, on a .c-and-.h basis, "
        "crypto/ 350,280, ssl/ 115,280, providers/ 87,318 and test/ 214,064. The bases differ. "
        "The per-directory figures count .c and .h together, the 808,625 total is .c only, and "
        "crypto/asn1 (16,350) and crypto/x509 (33,494) are quoted .c-only so the 6.2% share compares "
        "like with like. Exported-symbol manifests were read as one symbol per line: util/libcrypto.num "
        "(5,729) and util/libssl.num (628). No build, test, benchmark or network call was run against "
        "the project, and no advisory database was ingested; that absence is the gap this report "
        "reports. Objective: eliminate the memory-unsafety class where OpenSSL decodes "
        "attacker-controlled input without breaking the exported ABI or FIPS validation. User-supplied "
        "facts: none. No Amdahl calculation appears; the objective is safety, and substituting a line "
        "share for a time share would be a method error. Confidence is LOW and robustness INDETERMINATE "
        "by the method's own definitions, because two of the four gates are UNKNOWN and the candidate "
        "scopes span two orders of magnitude. This is a structured decision protocol, not a statistical "
        "predictor. DEFER–MEASURE here means the evidence to choose does not exist yet. It does not mean "
        "Rust cannot help.",
        "仓库：github.com/openssl/openssl，commit cdcb6ad，浅克隆，6,152 个受版本控制的文件。范围：整个仓库，"
        "候选抽取组件是 crypto/asn1 与 crypto/x509。采样：1,695 个文件、808,625 行 C；按 .c 与 .h 合计的口径，"
        "crypto/ 350,280 行，ssl/ 115,280 行，providers/ 87,318 行，test/ 214,064 行。口径不一样。"
        "目录级数字是 .c 与 .h 合计，808,625 这个总数只算 .c，crypto/asn1（16,350）与 crypto/x509（33,494）"
        "也只算 .c，这样 6.2% 才是同口径比较。导出符号清单按每行一个符号读取：util/libcrypto.num 5,729 个，"
        "util/libssl.num 628 个。没有对项目做过任何构建、测试、基准或网络调用，也没有导入任何 advisory 数据库；"
        "这份缺失正是本报告要报告的缺口。目标：在 OpenSSL 解析攻击者可控输入的地方消除内存不安全这一缺陷类，"
        "同时不破坏导出 ABI 与 FIPS 验证。用户提供的事实：无。本报告不做 Amdahl 计算；目标是安全，"
        "用行数占比顶替时间占比属于方法错误。按方法自身的定义，confidence 为 LOW，robustness 为 INDETERMINATE："
        "四道门里有两道停在 UNKNOWN，候选范围跨了两个数量级。这是一套结构化决策协议，不是统计预测器。"
        "这里的 DEFER–MEASURE 是说，用来做选择的证据还不存在。它不是说 Rust 帮不上忙。"
    ),
    "footer": ("public repository · static analysis at commit cdcb6ad · no build, benchmark or network call",
               "公开仓库 · 在 commit cdcb6ad 上做静态分析 · 无构建、基准或网络调用"),
}
